import type { AdminTab, CollectionKey } from "./types"

export const collectionLabels: Record<CollectionKey, string> = {
  products: "Produits",
  categories: "Catégories",
  technologies: "Technologies",
  news: "Actualités",
  faq: "FAQ",
  distributors: "Distributeurs",
  heroSlides: "Hero — Slides",
  stats: "Stats — Chiffres",
  marquee: "Marquee — Promesses",
  campaign: "Campaign",
  homeSections: "Sections Accueil",
  smartPage: "Page Smart Home",
  techPage: "Page Technologies",
  newsPage: "Page Actualités",
  aboutPage: "Page À propos",
  supportPage: "Page Support",
}

export type CollectionGroup = {
  id: string
  label: string
  keys: CollectionKey[]
}

export const collectionGroups: CollectionGroup[] = [
  {
    id: "catalogue",
    label: "Catalogue",
    keys: ["products", "categories", "technologies", "news", "faq", "distributors"],
  },
  {
    id: "site-content",
    label: "Contenu du site",
    keys: [
      "heroSlides",
      "stats",
      "marquee",
      "campaign",
      "homeSections",
      "smartPage",
      "techPage",
      "newsPage",
      "aboutPage",
      "supportPage",
    ],
  },
]

// Labels des champs de collections (données métier)
export const fieldLabels: Record<string, string> = {
  id: "Identifiant",
  name: "Nom",
  label: "Libellé",
  title: "Titre",
  description: "Description",
  excerpt: "Extrait",
  content: "Contenu",
  image: "Image principale",
  images: "Galerie d'images",
  badges: "Badges",
  capacity: "Capacité",
  energy_class: "Classe énergétique",
  energyClass: "Classe énergétique",
  connectivity: "Connectivité",
  technologies: "Technologies",
  noise_level: "Niveau sonore",
  noiseLevel: "Niveau sonore",
  dimensions: "Dimensions",
  features: "Caractéristiques",
  color: "Couleur",
  is_new: "Nouveauté",
  isNew: "Nouveauté",
  stock: "Stock",
  is_active: "Actif",
  isActive: "Actif",
  slug: "Slug",
  sort_order: "Ordre",
  subcategories: "Sous-catégories",
  tag: "Tag",
  subtitle: "Sous-titre",
  cta: "Bouton principal",
  ctaSec: "Bouton secondaire",
  ctaHref: "Lien bouton principal",
  ctaSecHref: "Lien bouton secondaire",
  icon: "Icône",
  benefit: "Bénéfice",
  category: "Catégorie",
  category_slug: "Catégorie (slug)",
  subcategory: "Sous-catégorie",
  compatible_categories: "Catégories compatibles",
  compatibleCategories: "Catégories compatibles",
  reference: "Référence",
  question: "Question",
  answer: "Réponse",
  published_at: "Date de publication",
  date: "Date",
  is_published: "Publié",
  wilaya: "Wilaya",
  commune: "Commune",
  address: "Adresse",
  phone: "Téléphone",
  email: "Email",
  latitude: "Latitude",
  longitude: "Longitude",
  w: "Largeur",
  h: "Hauteur",
  d: "Profondeur",
  badge: "Badge",
  darkImage: "Image carte sombre",
  darkTag: "Tag carte sombre",
  darkTitle: "Titre carte sombre",
  darkSpecs: "Specs carte sombre",
  darkHref: "Lien carte sombre",
  lightImage: "Image carte claire",
  lightTag: "Tag carte claire",
  lightTitle: "Titre carte claire",
  lightSpecs: "Specs carte claire",
  lightHref: "Lien carte claire",
  href: "Lien bouton",
  value: "Valeur",
  suffix: "Suffixe",
}

// Labels spécifiques aux pages éditoriales (smart, tech, news, about, support)
export const pageFieldLabels: Record<string, string> = {
  categoriesEyebrow: "Catégories — surtitre",
  categoriesTitle: "Catégories — titre",
  lineupEyebrow: "Line-up — surtitre",
  lineupTitle: "Line-up — titre",
  lineupIntro: "Line-up — intro",
  lineupOutro: "Line-up — conclusion",
  lineupWashingTitle: "Line-up lavage — titre",
  lineupWashingDesc: "Line-up lavage — texte",
  lineupSmallTitle: "Line-up petit électro — titre",
  lineupSmallDesc: "Line-up petit électro — texte",
  lineupWaterTitle: "Line-up chauffe-eau — titre",
  lineupWaterDesc: "Line-up chauffe-eau — texte",
  lineupHomeCareTitle: "Line-up entretien — titre",
  lineupHomeCareDesc: "Line-up entretien — texte",
  lineupFountainsTitle: "Line-up fontaines — titre",
  lineupFountainsDesc: "Line-up fontaines — texte",
  lineupCookingTitle: "Line-up cuisson — titre",
  lineupCookingDesc: "Line-up cuisson — texte",
  featuredSubtitle: "Vedettes — surtitre",
  featuredTitle: "Vedettes — titre",
  smartEyebrow: "Smart Home — surtitre",
  smartTitle: "Smart Home — titre",
  smartDesc: "Smart Home — texte",
  smartCta: "Smart Home — bouton",
  smartImage: "Smart Home — image",
  smartFeat1Title: "Smart atout 1 — titre",
  smartFeat1Desc: "Smart atout 1 — texte",
  smartFeat2Title: "Smart atout 2 — titre",
  smartFeat2Desc: "Smart atout 2 — texte",
  smartFeat3Title: "Smart atout 3 — titre",
  smartFeat3Desc: "Smart atout 3 — texte",
  smartFeat4Title: "Smart atout 4 — titre",
  smartFeat4Desc: "Smart atout 4 — texte",
  smartBadgeTitle: "Smart badge — titre",
  smartBadgeSubtitle: "Smart badge — sous-titre",
  smartEnergyLabel: "Smart énergie — libellé",
  smartEnergyValue: "Smart énergie — valeur",
  techSubtitle: "Technologies — surtitre",
  techTitle: "Technologies — titre",
  newsSubtitle: "Actus — surtitre",
  newsTitle: "Actus — titre",
  supportSubtitle: "Support — surtitre",
  supportTitle: "Support — titre",
  supportDesc: "Support — texte",
  supportCta1: "Support — bouton 1",
  supportCta2: "Support — bouton 2",
  supportFeatNoticesTitle: "Support notices — titre",
  supportFeatNoticesDesc: "Support notices — texte",
  supportFeatAssistanceTitle: "Support assistance — titre",
  supportFeatAssistanceDesc: "Support assistance — texte",
  supportFeatPartsTitle: "Support pièces — titre",
  supportFeatPartsDesc: "Support pièces — texte",
  supportFeatFaqTitle: "Support FAQ — titre",
  supportFeatFaqDesc: "Support FAQ — texte",
  heroEyebrow: "Smart hero — surtitre",
  heroTitle: "Smart hero — titre",
  heroDesc: "Smart hero — texte",
  heroCta1: "Smart hero — bouton 1",
  heroCta2: "Smart hero — bouton 2",
  heroImage: "Smart hero — image",
  badgeTitle: "Smart badge — titre",
  badgeSubtitle: "Smart badge — sous-titre",
  chartLabel: "Smart conso — libellé",
  chartValue: "Smart conso — valeur",
  step1Title: "Smart étape 1 — titre",
  step1Desc: "Smart étape 1 — texte",
  step2Title: "Smart étape 2 — titre",
  step2Desc: "Smart étape 2 — texte",
  step3Title: "Smart étape 3 — titre",
  step3Desc: "Smart étape 3 — texte",
  featSubtitle: "Smart atouts — surtitre",
  featTitle: "Smart atouts — titre",
  featDesc: "Smart atouts — texte",
  compatEyebrow: "Smart compatibles — surtitre",
  compatTitle: "Smart compatibles — titre",
  testiQuote: "Smart témoignage — citation",
  testiAuthor: "Smart témoignage — auteur",
  testiCity: "Smart témoignage — ville",
  appSubtitle: "Smart app — surtitre",
  appTitle: "Smart app — titre",
  appDesc: "Smart app — texte",
  appSecure: "Smart app — sécurité",
  techHeroSubtitle: "Tech hero — surtitre",
  techHeroTitle: "Tech hero — titre",
  techHeroDesc: "Tech hero — texte",
  stat1Value: "Tech stat 1 — valeur",
  stat1Label: "Tech stat 1 — libellé",
  stat2Value: "Tech stat 2 — valeur",
  stat2Label: "Tech stat 2 — libellé",
  stat3Value: "Tech stat 3 — valeur",
  stat3Label: "Tech stat 3 — libellé",
  stat4Value: "Tech stat 4 — valeur",
  stat4Label: "Tech stat 4 — libellé",
  filterAll: "Tech filtre — tout",
  filterConnectivity: "Tech filtre — connectivité",
  filterEco: "Tech filtre — éco",
  filterHygiene: "Tech filtre — hygiène",
  filterConservation: "Tech filtre — conservation",
  ctaTitle: "Tech CTA — titre",
  ctaDesc: "Tech CTA — texte",
  ctaButton: "Tech CTA — bouton",
  newsHeroEyebrow: "Actus hero — surtitre",
  newsHeroTitle: "Actus hero — titre",
  newsHeroDesc: "Actus hero — texte",
  newsStatArticles: "Actus stat — libellé articles",
  newsStatCategories: "Actus stat — libellé catégories",
  newsSectionEyebrow: "Actus section — surtitre",
  newsSectionTitle: "Actus section — titre",
  newsFilterAll: "Actus filtre — tout",
  newsFeaturedBadge: "Actus vedette — badge",
  newsFeaturedReadTime: "Actus vedette — durée",
  newsCardReadTime: "Actus carte — durée",
  newsEmpty: "Actus — texte vide",
  newsSupportEyebrow: "Actus support — surtitre",
  newsSupportTitle: "Actus support — titre",
  newsSupportButton: "Actus support — bouton",
  aboutHeroSubtitle: "À propos hero — surtitre",
  aboutHeroTitle: "À propos hero — titre",
  aboutHeroDesc: "À propos hero — texte",
  aboutHeroImage: "À propos hero — image",
  aboutStat1Value: "À propos stat 1 — valeur",
  aboutStat1Label: "À propos stat 1 — libellé",
  aboutStat2Value: "À propos stat 2 — valeur",
  aboutStat2Label: "À propos stat 2 — libellé",
  aboutStat3Value: "À propos stat 3 — valeur",
  aboutStat3Label: "À propos stat 3 — libellé",
  aboutStat4Value: "À propos stat 4 — valeur",
  aboutStat4Label: "À propos stat 4 — libellé",
  aboutIntroTitle: "À propos intro — titre",
  aboutIntroParagraphs: "À propos intro — paragraphes",
  aboutTagline: "À propos — signature",
  aboutMissionSubtitle: "À propos mission — surtitre",
  aboutMissionTitle: "À propos mission — titre",
  aboutMissionDesc1: "À propos mission — texte 1",
  aboutMissionDesc2: "À propos mission — texte 2",
  aboutMissionCta1: "À propos mission — bouton 1",
  aboutMissionCta2: "À propos mission — bouton 2",
  aboutMissionImage: "À propos mission — image",
  aboutQualityBadge: "À propos qualité — badge",
  aboutQualityBadgeSub: "À propos qualité — sous-badge",
  aboutValuesSubtitle: "À propos valeurs — surtitre",
  aboutValuesTitle: "À propos valeurs — titre",
  aboutValuesItems: "À propos valeurs — liste",
  aboutHistorySubtitle: "À propos histoire — surtitre",
  aboutHistoryTitle: "À propos histoire — titre",
  aboutHistoryMilestones: "À propos histoire — étapes",
  aboutCtaTitle: "À propos CTA — titre",
  aboutCtaDesc: "À propos CTA — texte",
  aboutCtaButton1: "À propos CTA — bouton 1",
  aboutCtaButton2: "À propos CTA — bouton 2",
  supHeroEyebrow: "Support hero — surtitre",
  supHeroTitle: "Support hero — titre",
  supHeroDesc: "Support hero — texte",
  supHeroCta1: "Support hero — bouton 1",
  supHeroCta2: "Support hero — bouton 2",
  supHeroImage: "Support hero — image",
  supBadgeTitle: "Support badge — titre",
  supBadgeSubtitle: "Support badge — sous-titre",
  supChartLabel: "Support conso — libellé",
  supChartValue: "Support conso — valeur",
  supStep1Title: "Support étape 1 — titre",
  supStep1Desc: "Support étape 1 — texte",
  supStep2Title: "Support étape 2 — titre",
  supStep2Desc: "Support étape 2 — texte",
  supStep3Title: "Support étape 3 — titre",
  supStep3Desc: "Support étape 3 — texte",
  supFeatSubtitle: "Support atouts — surtitre",
  supFeatTitle: "Support atouts — titre",
  supFeatDesc: "Support atouts — texte",
  supFeatures: "Support atouts — liste",
  supCompatEyebrow: "Support compatibles — surtitre",
  supCompatTitle: "Support compatibles — titre",
  supTestiQuote: "Support témoignage — citation",
  supTestiAuthor: "Support témoignage — auteur",
  supTestiCity: "Support témoignage — ville",
  supAppSubtitle: "Support app — surtitre",
  supAppTitle: "Support app — titre",
  supAppDesc: "Support app — texte",
  supAppSecure: "Support app — sécurité",
}

export const IMAGE_KEYS = new Set([
  "image",
  "logoUrl",
  "logo_url",
  "faviconUrl",
  "favicon_url",
  "darkImage",
  "lightImage",
  "smartImage",
  "heroImage",
  "aboutHeroImage",
  "aboutMissionImage",
  "supHeroImage",
])
export const GALLERY_KEYS = new Set(["images", "gallery"])

// Champs qui doivent occuper toute la largeur du formulaire
export const WIDE_FIELD_KEYS = new Set([
  "description",
  "content",
  "excerpt",
  "subtitle",
  "title",
  "answer",
  "question",
  "lineupIntro",
  "lineupOutro",
  "aboutIntroParagraphs",
  "aboutMissionDesc1",
  "aboutMissionDesc2",
  "aboutCtaDesc",
  "newsHeroDesc",
  "newsSectionTitle",
  "techHeroDesc",
  "ctaDesc",
  "heroDesc",
  "supHeroDesc",
  "supFeatDesc",
  "testiQuote",
  "supTestiQuote",
])

export const defaultPages = {
  home: {
    title: "Une propreté nouvelle génération.",
    description:
      "Des appareils pensés pour une maison plus simple, plus confortable et plus intelligente.",
  },
  contact: { email: "contact@aurex.dz", phone: "+213 21 XX XX XX", address: "Alger, Algérie" },
  seo: {
    title: "AUREX",
    description: "Électroménager premium en Algérie",
    keywords: "AUREX, électroménager, Algérie",
  },
}

export type PagesState = typeof defaultPages

export const defaultTheme = { primary: "#0A2463", accent: "#1E5EF3", surface: "#F9FAFB" }

export type ThemeState = typeof defaultTheme

// Sidebar glyphs — kept as quiet geometric marks rather than emoji.
export const icons: Record<AdminTab, string> = {
  overview: "◈",
  collections: "▦",
  users: "◉",
  pages: "▭",
  site: "⬢",
  theme: "⬣",
  backup: "⧉",
  history: "◷",
}

// Overview stat accents cycle through the brand's restrained palette.
export const statAccents = ["#2F5FE8", "#B08D4F", "#0A2342", "#1F8A5F", "#B08D4F", "#2F5FE8"]

export function pretty(value: unknown) {
  return JSON.stringify(value, null, 2)
}
